mlrun/demos

image_classification/mlrun_mpijob_classify.ipynb, image_classification/nuclio-serving-tf-images.ipynb
change fixed path to os.getcwd, add mising pip installs and explanation
=> Add descriptions and change paths

README.md
@yaronha please merge. Note that this isn't a full doc review, I just fixed some basic issues that I noticed without reading the full file (typos, spacing and line breaks, etc.).
Note that I also removed broken demo links and marked the NetOps demo as TBD (like the LightGBM demo).
=> [DOC REVIEW] README (#1): Basic fixes & improvements [IG-13721]

churn/churn-project.ipynb, churn/project/project.yaml, churn/project/workflow.py
* fixed data url, now retrieving data from mlrun demos master, churn project folder
* fixed `xgb.outputs[test_set]` label
* added `workflow.uid`
* uncommented retrieve mlrun-db `list_runs`
* other minor fixes
=> minor fixes, running v0.4.8

.github/workflows/release.yaml, Makefile
In order for the action to work a secret should be set in the repo named `RELEASE_GITHUB_ACCESS_TOKEN` and the value should be an access token with workflow and repo scopes.
I'll set it in the `mlrun/demos` with an access token of @mlrun-iguazio
=> Add github action to automatically push to release branch on release

realtime-face-recognition/README.md, realtime-face-recognition/client/README.md, realtime-face-recognition/client/video_capture.py, realtime-face-recognition/models.py, realtime-face-recognition/notebooks/face-recognition.ipynb, realtime-face-recognition/notebooks/functions/encode_images.py, realtime-face-recognition/notebooks/nuclio-api-serving.ipynb
fix real-time face recognition demo to work with 0.5.4 mlrun version and 2.10 iguazio version
=> fix real-time face recognition demo

.github/workflows/release.yaml, Makefile
=> Fixing release CI

customer-churn-prediction/churn-project.ipynb
=> [Churn] Update workflow

stock-analysis/project.ipynb
adding missing handler for running the train function
=> Fix stocks handler

model-deployment-pipeline/project.ipynb, realtime-face-recognition/notebooks/face-recognition.ipynb
These changes should also be merged to any other active branches.
=> [IG-17510] [SITE-RESTRUCT] Update doc-site URLs (v3.0.0 doc-site restructure)

getting-started-tutorial/01-mlrun-basics.ipynb, getting-started-tutorial/04-pipeline.ipynb, howto/converting-to-mlrun/mlrun-code.ipynb, howto/converting-to-mlrun/model-serving.ipynb, howto/converting-to-mlrun/original-code.ipynb, image-classification-with-distributed-training/horovod-project.ipynb, stock-analysis/functions/download_pretrained_model.py, stock-analysis/project.ipynb
All the offline datasets tree are under /v3io/bigdata/demos-data/iguazio/. 
I should be created on cluster creation.
=> Initial version

README.md
=> Corrections to the demos and English in the Readme file.

README.md
Added demos to the "in this document" section
=> Added demos to the section of "in this document".

mask-detection/1-training-and-evaluation.ipynb
Updated the TF version from 2.4.1 to 2.7.0.
=> [Mask Detection] Updated TF version

getting-started-tutorial/01-mlrun-basics.ipynb
Resolved marked down text issue
=> [Getting started] Resolved marked down text issue

mask-detection/2-serving.ipynb, mask-detection/3-automatic-pipeline.ipynb
Regarding this ticket: [IG-20681](https://jira.iguazeng.com/browse/IG-20681)
Increase the serving functions readiness timeout in both second and third notebooks.
=> [Mask Detection] - Increase the serving functions readiness timeout

.github/workflows/release.yaml, Makefile, howto/spark/spark_read_csv.py, mask-detection/pytorch/custom-objects/mask_detection_dataset.py, mask-detection/pytorch/custom-objects/mask_detection_mobilenet_v2.py, mask-detection/pytorch/serving.py, mask-detection/pytorch/training-and-evaluation.py, mask-detection/tf-keras/serving.py, mask-detection/tf-keras/training-and-evaluation.py, network-operations/src/generator.py, network-operations/src/metric_configurations.yaml, network-operations/src/workflow.py, news-article-nlp/nlp_transformations.py
=> Add Copyright Disclaimer

stocks-prediction/04_model_serving.ipynb, stocks-prediction/06_grafana_view.ipynb
moving serving scheduling from 06_grafana_view to 04_model_serving
=> [Stocks] model serving scheduling

news-article-nlp/news_article_nlp.ipynb
* graph semantics update + adding comments for CE (redis)
* one article link deprecated - changes all to new ones
=> [news_article_nlp] updating graph + article links

mask-detection/1-training-and-evaluation.ipynb, mask-detection/3-automatic-pipeline.ipynb
adding slash to the end of dataset_path for open_archive function (to support dir logging)
=> [mask-detection] dataset path open archive

mask-detection/pytorch/training-and-evaluation.py
using abspath on dataset_path doesn't yield parent directory
=> [mask-detection] fixing custom object path

stocks-prediction/src/stocks.py
update notebook to collect number of tickers
=> add logging to stocks file

tutorials/.test
[ML-3629](https://jira.iguazeng.com/browse/ML-3629)
=> [Tutorials] Fix name of tutorial in `.test` file

stocks-prediction/01_ingest_news.ipynb
01_ingest_news version fix transformers==4.11.3
=> [stocks-prediction] fix transformers version

update_demos.sh
=> Revert "updating update-demos script"

network-operations/02-training-and-deployment.ipynb, network-operations/src/workflow.py, stocks-prediction/03_train_model.ipynb, stocks-prediction/05_stocks_pipeline.ipynb, stocks-prediction/src/serving_stocks.py, stocks-prediction/src/train_stocks.py
entity_timestamp_column to timestamp_for_filtering in fstore.get_offline_features()
=> [update] api change

howto/converting-to-mlrun/original-code.ipynb
=> [howto] remove silent + updating params

tutorials/01-mlrun-basics.ipynb
since installing mlrun[complete] will install latest mlrun release (1.4.1 atm) scikit-learn version are missalinged
=> [tutorials] update 01-basics

update_demos.sh
=> [update-demos] fixing issues

fraud-prevention-feature-store/01-ingest-datasources.ipynb, network-operations/01-ingest.ipynb, stocks-prediction/01_ingest_news.ipynb, stocks-prediction/02_ingest_stocks.ipynb
[ML-4220](https://jira.iguazeng.com/browse/ML-4220)
Depends on https://github.com/mlrun/mlrun/pull/4232.
=> [stocks-prediction] Use new API, `deploy_ingestion_service_v2`

mask-detection/1-training-and-evaluation.ipynb, mask-detection/3-automatic-pipeline.ipynb
=> [mask-detection] dataset_path to an accessible path

network-operations/01-ingest.ipynb, network-operations/src/generator.py
=> [netops] Reading data from wasabi 1.6.x

network-operations/01-ingest.ipynb, network-operations/src/generator.py
=> [netops] Reading data from wasabi 1.7.x
